name: CI

on:
  workflow_dispatch:
  push:
    branches: [default]

jobs:
  version:
    uses: katastroma/skeuotheke/.github/workflows/version.yaml@v0
    permissions:
      contents: write
    with:
      GH_APP_ID: ${{ vars.SKEUOTHEKE_GH_APP_CLIENT_ID }}
    secrets:
      GH_APP_PRIVATE_KEY: ${{ secrets.SKEUOTHEKE_GH_APP_PRIVATE_KEY }}
