name: PR

on:
  workflow_dispatch:
  pull_request:
    branches: [default]

jobs:
  commit-check:
    name: CI
    uses: katastroma/skeuotheke/.github/workflows/commit-check.yaml@v0

  version-check:
    name: CI
    uses: katastroma/skeuotheke/.github/workflows/version-check.yaml@v0

  ci-go:
    name: CI
    uses: katastroma/skeuotheke/.github/workflows/ci-go.yaml@v0
